config/routes.rb
# -*- encoding : utf-8 -*-
Defindex::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  resources :home, :only => [:index]
  root :to => 'home#index'

  resources :blog, :only => [:index, :show] do
    get 'page/:page', :action => :index, :on => :collection
  end
  resources :tag, :only => [:show]do
    get 'page/:page', :action => :show, :on => :collection
  end
  resources :comments , :only => [:create]

  # The priority is based upon order of creat
  #ion:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
     namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
       resources :home, only: [:index]
       resources :posts
       resources :tags
       root :to => 'home#index'
     end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/tag.rb
# -*- encoding : utf-8 -*-
class Tag < ActiveRecord::Base
  extend FriendlyId
  attr_accessible :name
  has_and_belongs_to_many :posts


  friendly_id :name, use: :slugged

  def self.tokens(query)
  tags = where("name like ?", "%#{query}%")
  if tags.empty?
    [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
  else
    tags
  end
end

def self.ids_from_tokens(tokens)
  tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
  tokens.split(',')
end
end

app/controllers/admin/tags_controller.rb
# -*- encoding : utf-8 -*-
class Admin::TagsController < Admin::BaseController
def index
  @tags = Tag.order(:name)
  respond_to do |format|
    format.html
    format.json { render json: @tags.tokens(params[:q]) }
    format.xml {render xml: @tags}
  end
end
end

app/controllers/tag_controller.rb
# -*- encoding : utf-8 -*-
class TagController < ApplicationController
  def show
    @tag = Tag.find(params[:id], include: [:posts])
    @posts = @tag.posts.published.page params[:page]
  end
end

app/helpers/admin/tags_helper.rb
# -*- encoding : utf-8 -*-
module Admin::TagsHelper
end

app/helpers/tag_helper.rb
# -*- encoding : utf-8 -*-
module TagHelper
end

app/views/tag/show.html.erb
<% content_for :main_menu do %>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to 'Blog', blog_index_path, class: 'active' %></li>
<% end %>
  <div id="left">
    <% @posts.each do |post| %>
    <div class="post">
      <h2><%= link_to post.title, blog_path(post) %></h2>
      <ul class="tags">
         <% post.tags.each do |tag| %>
        <li><%= link_to tag.name, tag_path(tag) %></a></li>
      <% end %>
      </ul>
      <%= link_to (image_tag post.cover(:medium), class: 'cover'), blog_path(post) %>
    </div>
   <% end %>
  </div><!-- end div left -->
  <div id="right">
  <!-- LOMADEE - BEGIN -->
<script type="text/javascript" language="javascript">
	lmd_source="24791001";
	lmd_si="33412755";
	lmd_pu="22264751";
	lmd_c="BR";
	lmd_wi="120";
	lmd_he="600";
</script>
<script src="http://image.lomadee.com/js/ad_lomadee.js" type="text/javascript" language="javascript"></script>
<!-- LOMADEE - END -->
  </div><!-- end div right -->