config/routes.rb
# -*- encoding : utf-8 -*-
Defindex::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  resources :home, :only => [:index]
  root :to => 'home#index'

  resources :blog, :only => [:index, :show] do
    get 'page/:page', :action => :index, :on => :collection
  end
  resources :tag, :only => [:show]do
    get 'page/:page', :action => :show, :on => :collection
  end
  resources :comments , :only => [:create]

  # The priority is based upon order of creat
  #ion:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
     namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
       resources :home, only: [:index]
       resources :posts
       resources :tags
       root :to => 'home#index'
     end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/ckeditor/asset.rb
# -*- encoding : utf-8 -*-
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
# -*- encoding : utf-8 -*-
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data
	
	def url_thumb
	  @url_thumb ||= Ckeditor::Utils.filethumb(filename)
	end
end

app/models/ckeditor/picture.rb
# -*- encoding : utf-8 -*-
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
	                  :styles => { :content => '800>', :thumb => '118x100#' }
	
	validates_attachment_size :data, :less_than => 2.megabytes
	validates_attachment_presence :data
	
	def url_content
	  url(:content)
	end
end

app/models/comment.rb
# -*- encoding : utf-8 -*-
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :post_id, :approved, :body, :name

  validates :name, :body, :post_id, :presence => true

  scope :approved, where(approved: true)
end

app/models/post.rb
# -*- encoding : utf-8 -*-
class Post < ActiveRecord::Base
  extend FriendlyId
  attr_accessible :author, :body, :published, :slug, :title, :cover, :tag_tokens, :comments_attributes
  attr_reader :tag_tokens, :summary
  has_and_belongs_to_many :tags
  has_many :comments, :dependent => :destroy

  friendly_id :title, use: :slugged

  has_attached_file :cover, :styles => { :medium => "800x215#", :thumb => "100x30>" }

  accepts_nested_attributes_for :comments, :allow_destroy => true

  default_scope order('created_at DESC')
  scope :published, where(published: true)

  def tag_tokens=(tokens)
    self.tag_ids = Tag.ids_from_tokens(tokens)
  end

  def summary
    summary = body.gsub(/(<[^>]*>)|\n|\t/s) {" "}
    summary.truncate(140).html_safe
  end
end

app/models/tag.rb
# -*- encoding : utf-8 -*-
class Tag < ActiveRecord::Base
  extend FriendlyId
  attr_accessible :name
  has_and_belongs_to_many :posts


  friendly_id :name, use: :slugged

  def self.tokens(query)
  tags = where("name like ?", "%#{query}%")
  if tags.empty?
    [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
  else
    tags
  end
end

def self.ids_from_tokens(tokens)
  tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
  tokens.split(',')
end
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/base_controller.rb
# -*- encoding : utf-8 -*-
class Admin::BaseController < ApplicationController
before_filter :authenticate_user!
layout 'admin'
end

app/controllers/admin/home_controller.rb
# -*- encoding : utf-8 -*-
class Admin::HomeController < Admin::BaseController
  def index
  end
end

app/controllers/admin/posts_controller.rb
# -*- encoding : utf-8 -*-
class Admin::PostsController < Admin::BaseController
  before_filter :get_post, :only => [:show, :edit, :update, :destroy]


  def index
    @search = Post.search(params[:search])
    @posts = @search.page params[:page]
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      redirect_to [:admin,@post], notice: 'Post criado com sucesso.'
    else
      render 'new'
    end
  end

  def update
    if @post.update_attributes(params[:post])
      redirect_to [:admin,@post], notice: 'Post atualizado'
    else
      render 'edit'
    end
  end

  def destroy
    if @post.destroy
      redirect_to admin_posts_path, notice: "Post excluido"
    else
      redirect_to admin_posts_path, notice: "Post não excluido"
    end
  end


  private
  def get_post
    @post = Post.find(params[:id])
  end

end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_controller.rb
# -*- encoding : utf-8 -*-
class BlogController < ApplicationController

  def index
    @search = Post.published.search(params[:search])
    @posts = @search.page(params[:page]).per(15)
  end

  def show
    @post = Post.published.find(params[:id], include: [:comments])
    @comment = Comment.new
    @title = "#{@post.title} - "
    @description = @post.summary
  end

end

app/controllers/comments_controller.rb
# -*- encoding : utf-8 -*-
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(params[:comment])
    if @comment.save
      Notifier.comment(@comment).deliver
      redirect_to blog_path(@comment.post_id), notice: 'Seu comentário está aguardando aprovação'
    else
      redirect_to blog_index_path, alert: 'Não foi possivel gravar seu comentário'
    end
  end
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tag_controller.rb
# -*- encoding : utf-8 -*-
class TagController < ApplicationController
  def show
    @tag = Tag.find(params[:id], include: [:posts])
    @posts = @tag.posts.published.page params[:page]
  end
end

app/helpers/admin/home_helper.rb
# -*- encoding : utf-8 -*-
module Admin::HomeHelper
end

app/helpers/admin/posts_helper.rb
# -*- encoding : utf-8 -*-
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
# -*- encoding : utf-8 -*-
module Admin::TagsHelper
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/blog_helper.rb
# -*- encoding : utf-8 -*-
module BlogHelper
end

app/helpers/comments_helper.rb
# -*- encoding : utf-8 -*-
module CommentsHelper
end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/helpers/tag_helper.rb
# -*- encoding : utf-8 -*-
module TagHelper
end

app/views/admin/posts/_form.html.erb
<%= simple_nested_form_for [:admin,@post] do |f| %>
  <%= f.input :title %>
  <%= f.input :cover, as: :file %>
  <%= f.input :published %>
  <%= f.label :tag_tokes, 'Tags' %>
  <%= f.text_field :tag_tokens, data: {load: @post.tags} %>
  <%= f.input :body, :as => :ckeditor, :label => false, :input_html => { :toolbar => 'Full' }  %>
  <%#= f.cktext_area :body, :toolbar => 'Full', :width => 800, :height => 400 %>
  <h4>Comments</h4>
  <%= f.fields_for :comments do |comment_form| %>
  <fieldset class="nested">
    <%= comment_form.input :name %>
    <%= comment_form.input :body %>
    <%= comment_form.input :approved %>
    <%= comment_form.link_to_remove "Remove this comment" %>
  </fieldset>
<% end %>

  <div class="well actions">
    <%= f.button :submit, class: 'btn btn-primary'%>
    <%= link_to 'Cancel', admin_posts_path, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Dashboard", admin_root_path %> <span class="divider">/</span></li>
  <li><%= link_to "Posts", admin_posts_path %> <span class="divider">/</span></li>
  <li class="active">Edit Post <%= @post.title %></li>
</ul>
<%= render 'form' %>

app/views/admin/posts/index.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Dashboard", admin_root_path %> <span class="divider">/</span></li>
  <li class="active">Posts</li>
</ul>
<table class="table table-striped">
<thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Published</th>
      <th>Created at</th>
      <th colspan='3'>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title %></td>
        <td><%= post.published %></td>
        <td><%= post.created_at %></td>
        <td><%= link_to 'visualizar', [:admin,post] %></td>
        <td><%= link_to 'editar', [:edit,:admin,  post] %></td>
        <td><%= link_to 'excluir', [:admin,post], method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @posts, :theme => 'twitter-bootstrap' %>
<div class="well actions">
  <%= link_to 'Nova Postagem', new_admin_post_path, class: 'btn btn-success' %>
</div>

app/views/admin/posts/new.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Dashboard", admin_root_path %> <span class="divider">/</span></li>
  <li><%= link_to "Posts", admin_posts_path %> <span class="divider">/</span></li>
  <li class="active">New Post</li>
</ul>
<%= render 'form' %>

app/views/admin/posts/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Dashboard", admin_root_path %> <span class="divider">/</span></li>
  <li><%= link_to "Posts", admin_posts_path %> <span class="divider">/</span></li>
  <li class="active"><%= @post.title %></li>
</ul>

<table class="table table-striped">
  <tr>
    <td>Titulo</td>
    <td><%= @post.title %></td>
  </tr>
    <tr>
    <td>Image</td>
    <td><%= image_tag @post.cover(:thumb) %></td>
  </tr>
    <tr>
    <td>Published</td>
    <td><%= @post.published %></td>
  </tr>
    <tr>
    <td>Body</td>
    <td><%= sanitize(@post.body) %></td>
  </tr>
  <tr>
    <td>Tags</td>
    <td><%= @post.tags.map(&:name).join(' - ') %></td>
  </tr>
</table>
<h4>Comments</h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Comentário</th>
      <th>Approved</th>
      <th>Created at</th>
    </tr>
  </thead>
  <tbody>
  <% @post.comments.each do |comment| %>
    <tr>
      <td><%= comment.name %></td>
      <td><%= comment.body %></td>
      <td><%= comment.approved %></td>
      <td><%= comment.created_at %></td>
    </tr>
  <% end %>
</table>

<div class="well actions">
  <%= link_to 'Nova Postagem', new_admin_post_path, class: 'btn btn-success' %>
  <%= link_to 'Editar Postagem', edit_admin_post_path(@post), class: 'btn btn-warning' %>
  <%= link_to 'Voltar', admin_posts_path, class: 'btn' %>
</div> 