config/routes.rb
# -*- encoding : utf-8 -*-
Defindex::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  resources :home, :only => [:index]
  root :to => 'home#index'

  resources :blog, :only => [:index, :show] do
    get 'page/:page', :action => :index, :on => :collection
  end
  resources :tag, :only => [:show]do
    get 'page/:page', :action => :show, :on => :collection
  end
  resources :comments , :only => [:create]

  # The priority is based upon order of creat
  #ion:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
     namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
       resources :home, only: [:index]
       resources :posts
       resources :tags
       root :to => 'home#index'
     end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/ckeditor/asset.rb
# -*- encoding : utf-8 -*-
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
# -*- encoding : utf-8 -*-
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data
	
	def url_thumb
	  @url_thumb ||= Ckeditor::Utils.filethumb(filename)
	end
end

app/models/ckeditor/picture.rb
# -*- encoding : utf-8 -*-
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
	                  :styles => { :content => '800>', :thumb => '118x100#' }
	
	validates_attachment_size :data, :less_than => 2.megabytes
	validates_attachment_presence :data
	
	def url_content
	  url(:content)
	end
end

app/models/comment.rb
# -*- encoding : utf-8 -*-
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :post_id, :approved, :body, :name

  validates :name, :body, :post_id, :presence => true

  scope :approved, where(approved: true)
end

app/models/post.rb
# -*- encoding : utf-8 -*-
class Post < ActiveRecord::Base
  extend FriendlyId
  attr_accessible :author, :body, :published, :slug, :title, :cover, :tag_tokens, :comments_attributes
  attr_reader :tag_tokens, :summary
  has_and_belongs_to_many :tags
  has_many :comments, :dependent => :destroy

  friendly_id :title, use: :slugged

  has_attached_file :cover, :styles => { :medium => "800x215#", :thumb => "100x30>" }

  accepts_nested_attributes_for :comments, :allow_destroy => true

  default_scope order('created_at DESC')
  scope :published, where(published: true)

  def tag_tokens=(tokens)
    self.tag_ids = Tag.ids_from_tokens(tokens)
  end

  def summary
    summary = body.gsub(/(<[^>]*>)|\n|\t/s) {" "}
    summary.truncate(140).html_safe
  end
end

app/models/tag.rb
# -*- encoding : utf-8 -*-
class Tag < ActiveRecord::Base
  extend FriendlyId
  attr_accessible :name
  has_and_belongs_to_many :posts


  friendly_id :name, use: :slugged

  def self.tokens(query)
  tags = where("name like ?", "%#{query}%")
  if tags.empty?
    [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
  else
    tags
  end
end

def self.ids_from_tokens(tokens)
  tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
  tokens.split(',')
end
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_controller.rb
# -*- encoding : utf-8 -*-
class BlogController < ApplicationController

  def index
    @search = Post.published.search(params[:search])
    @posts = @search.page(params[:page]).per(15)
  end

  def show
    @post = Post.published.find(params[:id], include: [:comments])
    @comment = Comment.new
    @title = "#{@post.title} - "
    @description = @post.summary
  end

end

app/controllers/comments_controller.rb
# -*- encoding : utf-8 -*-
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(params[:comment])
    if @comment.save
      Notifier.comment(@comment).deliver
      redirect_to blog_path(@comment.post_id), notice: 'Seu comentário está aguardando aprovação'
    else
      redirect_to blog_index_path, alert: 'Não foi possivel gravar seu comentário'
    end
  end
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tag_controller.rb
# -*- encoding : utf-8 -*-
class TagController < ApplicationController
  def show
    @tag = Tag.find(params[:id], include: [:posts])
    @posts = @tag.posts.published.page params[:page]
  end
end

app/helpers/admin/home_helper.rb
# -*- encoding : utf-8 -*-
module Admin::HomeHelper
end

app/helpers/admin/posts_helper.rb
# -*- encoding : utf-8 -*-
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
# -*- encoding : utf-8 -*-
module Admin::TagsHelper
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/blog_helper.rb
# -*- encoding : utf-8 -*-
module BlogHelper
end

app/helpers/comments_helper.rb
# -*- encoding : utf-8 -*-
module CommentsHelper
end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/helpers/tag_helper.rb
# -*- encoding : utf-8 -*-
module TagHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Defindex" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "admin/application", :media => "all" %>
    <%= javascript_include_tag "admin/application" %>
    <link href="images/favicon.ico" rel="shortcut icon">

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Defindex</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Posts", admin_posts_path  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
       </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

  <%= yield :footer %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %> DefIndex: Consultoria e desenvolvimento de sites</title>
  <meta name="description” content=”<%= @description.blank? ? 'Criação e Desenvolvimento de sites utilizando Ruby on Rails.' : @description %>" />
  <meta property="og:title" content="<%= @title %> - DefIndex: Consultoria e desenvolvimento de sites" />
  <meta property="og:image" content="/assets/face-logo.png" />
  <meta property="og:description" content="<%= @description.blank? ? 'Criação e Desenvolvimento de sites utilizando Ruby on Rails.' : @description %>" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "2eb7af29-ff10-4117-8e05-a02160e9d186"}); </script>

  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
<%= yield :search %>
  <nav id="menu">
    <ul>
      <%= yield :main_menu %>
    </ul>
  </nav>
</div>
  <h1 id="logo">DefIndex Consultoria e desenvolvimento de sites<span></span></h1>
<div id="content">
      <% [:notice,:alert].each do |key|%>
        <% unless flash[key].blank? %>
          <div class="alert-message <%= key %>">
          <p><strong><%= flash[key]%></strong></p>
          </div>
        <% end %>
      <% end %>
  <%= yield %>
</div><!-- end div content -->
<footer id="footer">
<div id="footer-logo"><%= image_tag 'logo-footer.png', alt: 'defindex logo' %></div>
<div id="address">Rua 14, n°80 Centro, Caldas Novas - GO<br />
email: <a href="mailto:mgswolf@gmail.com">mgswolf@gmail.com</a> fone: (64)3453-1468 | (64) 9289-4076
</div>
<div id="social-buttons">
  <%= link_to image_tag("linkedin.png", class: "social"), "http://br.linkedin.com/in/mgswolf", target: "_blank" %>
  <%= link_to image_tag("twitter.png", class: "social"), "http://twitter.com/mgswolf", target: "_blank" %>
  <%= link_to image_tag("facebook.png", class: "social"), "http://facebook.com/defindex", target: "_blank" %>
  <%= link_to image_tag("google.png", class: "social"), "https://plus.google.com/114636792615741429493?
   rel=author", target: "_blank" %>

</div>
</footer>
</body>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-6293503-9']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</html>

app/views/notifier/comment.html.erb
Comentário em <%= link_to @comment.post.title, admin_post_url(@comment.post.id) %>
<br />
<strong><%= @comment.name %>:</strong>
<p>
  <%= @comment.body %>
</p>